x-aws-cluster: "daphne-cluster"
x-aws-vpc: "vpc-098fbf36bcf268c12"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: daphne_redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: daphne_rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
  neo4j:
    image: neo4j:latest
    ports: 
      - "7474:7474"
      - "7687:7687"
    container_name: daphne_neo4j
    environment: 
      - NEO4J_AUTH=neo4j/test
    ulimits:
      nofile:
        soft: 40000
        hard: 60000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
  graphql:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=<URL>
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=daphne
      - HASURA_GRAPHQL_AUTH_HOOK=<URL>
      - HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL=100
    container_name: daphne_graphql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
