services:
  daphne:
    build:
      dockerfile: ./build/Dockerfile
      context: .
    image: daphne:test
    volumes:
      - type: bind
        source: ${ROOT_DIR}/codebase
        target: /app/daphne
      - type: bind
        source: ${ROOT_DIR}/build/scripts
        target: /app/scripts
      - type: bind
        source: ${ROOT_DIR}/logs
        target: /app/logs
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - postgres
    tty: true
    container_name: daphne_server
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=daphne
      - POSTGRES_PASSWORD=daphne
      - POSTGRES_DB=daphne
    container_name: daphne_database
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: daphne_redis
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    hostname: "my-rabbitmq"
    container_name: daphne_rabbitmq
  neo4j:
    image: neo4j:latest
    ports: 
      - "7474:7474"
      - "7687:7687"
    container_name: daphne_neo4j
    volumes: 
      - ${ROOT_DIR}/databases/neo4j/data:/data
      - ${ROOT_DIR}/databases/neo4j/logs:/logs
    environment: 
      - NEO4J_AUTH=neo4j/test
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "6001:80"
    container_name: daphne_pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=daphne
      - PGADMIN_DEFAULT_PASSWORD=daphne
  graphql:
    image: hasura/graphql-engine:latest
    ports:
      - "6002:8080"
    depends_on: 
      - "postgres"
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://daphne:daphne@postgres:5432/daphne
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=daphne
      - HASURA_GRAPHQL_AUTH_HOOK=http://daphne:8001/
      - HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL=100
    container_name: daphne_graphql
  nodejs:
    image: node:latest
    ports:
      - "4001:4000"
      - "3000:3000"
    tty: true
    container_name: daphne_nodejs
    volumes:
      - type: bind
        source: ${ROOT_DIR}/databases/apollo
        target: /repos/apollo
      - type: bind
        source: ${ROOT_DIR}/databases/apollo-api
        target: /repos/apollo-api
  localstack:
    image: apazagab/localstack
    ports:
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4615:4566-4615"
    environment:
      - LOCALSTACK_API_KEY:3mfjxSfeMg
      - DEFAULT_REGION=us-east-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localhost
      - HOSTNAME_EXTERNAL=localhost
      - USER_SSL=true
      - SERVICES=serverless,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    container_name: daphne_aws_stack
  vassar:
    build: ${ROOT_DIR}/codebase/design-evaluator
    image: vassar:alpha
    volumes:
      - type: bind
        source: ${ROOT_DIR}/codebase/design-evaluator
        target: /app
    ports:
      - "9091:9091"
    environment:
      - AWS_ACCESS_KEY_ID=AKIAJVM34C5MCCWRJCCQ
      - AWS_SECRET_ACCESS_KEY=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
      - REQUEST_MODE=CRISP-ATTRIBUTES
      - GROUP_ID=1
      - PROBLEM_ID=4
      - APOLLO_URL=http://graphql:8080/v1/graphql
      - AWS_STACK_ENDPOINT=http://localstack:4576
      - EVAL_QUEUE_URL=http://localhost:4576/queue/vassar_queue
      - PRIVATE_QUEUE_NAME=vassar_private_queue
      - APOLLO_URL_WS=ws://graphql:8080/v1/graphql
    container_name: Vassar
    tty: true
  add:
    image: neo4j:latest
    ports: 
      - "7475:7474"
      - "7688:7687"
    container_name: add_database
    volumes: 
      - ${ROOT_DIR}/databases/neo4j_add/data:/data
      - ${ROOT_DIR}/databases/neo4j_add/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*
  add_ga:
    build: ${ROOT_DIR}/codebase/decisions
    image: add_server:beta
    volumes:
      - type: bind
        source: ${ROOT_DIR}/codebase/decisions
        target: /app
    environment:
      - AWS_ACCESS_KEY_ID=AKIAJVM34C5MCCWRJCCQ
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STACK_ENDPOINT=http://localstack:4576
      - NEO4J_URI=neo4j://add:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
      - PROBLEM=ClimateCentric
      - EVAL_QUEUE=add_queue
      - VASSAR_QUEUE=http://localhost:4576/queue/vassar_queue
    container_name: daphne_AddGA
    tty: true
